services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: stibo
      POSTGRES_PASSWORD: someDificultPassword
      POSTGRES_DB: stibo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stibo -d stibo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  quarkus-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-user-crud
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-db:5432/stibo_db
      QUARKUS_DATASOURCE_USERNAME: stibo
      QUARKUS_DATASOURCE_PASSWORD: someDificultPassword
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: