services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: stibo
      POSTGRES_PASSWORD: someDificultPassword
      POSTGRES_DB: stibo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stibo -d stibo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: